# Project information
site_name: OpenHolidays API
site_description: 'Documentation of the OpenHolidays API project'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://www.openholidaysapi.org/'

# Copyright
copyright:
  '&copy; 2025 STÜBER SYSTEMS GmbH : <a href="https://legal.stueber.de/en/imprint.php">Imprint</a> : <a href="https://legal.stueber.de/en/privacy.php">Privacy</a>'

# Repository
repo_name: 'On GitHub'
repo_url: 'https://github.com/openpotato/openholidaysapi.website'

# Theming
theme:
  name: material
  language: de
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: false
  favicon: 'assets/logos/favicon.ico'
  logo: 'assets/logos/logo.svg'
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html

# Social media & multi language
extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/openpotato.org
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@openpotato
  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: English
      lang: en

# Customization
extra_css:
  - assets/css/custom.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Navigation
nav:
  - Welcome: index.md
  - Reference:
    - Error messages: errors.md
  - Change Log:
    - Data: change-log-data.md
    - Web Service: change-log-webservice.md
  - Data Sources: sources.md
  - Client Libraries: libraries.md
  - Community: community.md
  - FAQ: faq.md
  - API: api.md